# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, default=1501.0, max_digits=6)),
                ('Best_Use', models.CharField(default='Commuter & Urban', max_length=80)),
                ('Range', models.DecimalField(decimal_places=0, default=21, max_digits=4)),
            ],
        ),
    ]
